services:
  microservice:
    build: .
    ports:
      - "127.0.0.1:8041:8041"
    volumes:
      - ./certs:/app/certs

  wiremock:
    build:
      context: .
      dockerfile: wiremock.Dockerfile
    ports:
      - "127.0.0.1:9091:9091"
    volumes:
      - ./certs:/wiremock/certs

volumes:
  certs:
